### ISSUE TITLE
Request to Add Turkish Translation of README

### ISSUE THREAD

**Issue by Nerzve** [gaze-network/gaze-indexer#45]
Hello,

I noticed that the current README is in English and would like to offer a Turkish translation. This could help Turkish-speaking users and contributors better understand the project.

## Proposed Solution:

1. Translate the README from English to Turkish.
2. Keep technical terms in English if they don't have direct Turkish equivalents.
3. Add a link to the Turkish version at the top of the existing README.

## Context:

I am a native Turkish speaker and can assist with the translation. The current English version is straightforward, but translating it will make it even more accessible. Let me know if you are open to this and if there are any guidelines I should follow.

Thank you!

**Comment by gazenw** [comment]
Hi @Rumeyst! Thank you for your offer! Feel free to open a PR with the Turkish version of README.md and we will review it. You should put it in `docs/README_tr.md` and add a link from the main `README.md` to your file. 🫡 

For guidelines, there's not much except keep the code and commands the exact same and try to keep the README simple and concise. The objective of the README is to tell the reader:
1. What Gaze Indexer is.
2. How to start running it from zero.
